#!/usr/bin/env bash
# Thomas Merkel <tm@core.io>
# Simple bash script to administrate remote SmartOS machines with
# vmadm and imgadm over openSSH. Keep it simple and stupid!

## Functions and other libs
. lib/utils.sh
. lib/shml.sh
. lib/vmadm.sh
. lib/imgadm.sh

## Parameters- and Optionsparser
# Params:
# - ${1} hypervisor
# Options:
# - ${2} vmadm
#   - ${3} create [TEMPLATE]
#   - ${3} *
# - ${2} imgadm
#   - ${3} *

hypervisor=${1}; shift
option=${1}; shift

# Verify if function exists
if [ -n "$(type -t ${option})" ] && [ "$(type -t ${option})" = function ]; then
	returnValues="$(${option} ${@})"
	if (( ${?} > 0 )); then
		echo ${returnValues}
		exit ${?}
	fi
	# Run command remotly
	echo "${returnValues}" | while read connect command; do
		case "${connect}" in
			ssh)
				ssh ${hypervisor} ${command} </dev/null
				;;
			scp)
				scp ${command% *} ${hypervisor}:${command#* }
				;;
			*)
				echo ${connect} ${hypervisor} ${command}
				;;
		esac
	done
else
	help
fi
